"""Config scaffolding helpers for ``helicon init``.

Generates a starter simulation config YAML with inline comments
explaining each field, so new users have a self-documenting template
to build on.
"""

from __future__ import annotations

_PRESET_TEMPLATES: dict[str, str] = {
    "custom": """\
# Helicon simulation config — generated by `helicon init`
# Edit the fields below, then run:  helicon run --config <this-file>

nozzle:
  type: solenoid          # solenoid | permanent_magnet
  coils:
    - z: 0.0              # axial position [m]
      r: 0.10             # coil radius [m]
      I: 20000            # coil current [A]
    - z: 0.20
      r: 0.12
      I: 15000
  domain:
    z_min: -0.20          # upstream boundary [m]
    z_max:  1.00          # downstream boundary [m]
    r_max:  0.40          # radial boundary [m]

plasma:
  n0: 1.0e18              # peak plasma density [m^-3]
  T_i_eV: 100             # ion temperature [eV]
  T_e_eV: 100             # electron temperature [eV]
  v_injection_ms: 50000   # axial injection velocity [m/s]
  species: H+             # ion species (H+, He+, Ar+, Xe+)
""",
    "sunbird": """\
# Helicon simulation config — Sunbird preset
# Based on a single-stage helicon thruster optimised for
# 1–5 kW RF power with 1000–3000 s Isp.

nozzle:
  type: solenoid
  coils:
    - z: 0.00
      r: 0.075
      I: 25000
    - z: 0.15
      r: 0.090
      I: 18000
  domain:
    z_min: -0.10
    z_max:  1.20
    r_max:  0.35

plasma:
  n0: 2.0e18
  T_i_eV: 120
  T_e_eV: 80
  v_injection_ms: 60000
  species: H+
""",
    "highpower": """\
# Helicon simulation config — high-power preset
# Suited for 10–100 kW class thrusters (deep-space missions).

nozzle:
  type: solenoid
  coils:
    - z: 0.00
      r: 0.15
      I: 80000
    - z: 0.25
      r: 0.18
      I: 60000
    - z: 0.50
      r: 0.20
      I: 40000
  domain:
    z_min: -0.25
    z_max:  2.00
    r_max:  0.80

plasma:
  n0: 5.0e18
  T_i_eV: 200
  T_e_eV: 150
  v_injection_ms: 80000
  species: Ar+
""",
}

AVAILABLE_PRESETS = list(_PRESET_TEMPLATES.keys())


def scaffold_config(preset: str = "custom") -> str:
    """Return a YAML config string for the given preset.

    Parameters
    ----------
    preset : str
        One of ``"custom"``, ``"sunbird"``, or ``"highpower"``.

    Returns
    -------
    str
        YAML text ready to write to a file.

    Raises
    ------
    ValueError
        If *preset* is not recognised.
    """
    if preset not in _PRESET_TEMPLATES:
        opts = ", ".join(AVAILABLE_PRESETS)
        raise ValueError(f"Unknown preset {preset!r}. Choose from: {opts}")
    return _PRESET_TEMPLATES[preset]
