"""Generate WarpX input files from MagNozzleX configuration.

Produces a WarpX-compatible input script for 2D RZ axisymmetric
magnetic nozzle simulations.
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path

from magnozzlex.config.parser import SimConfig

# Species mass table [kg]
SPECIES_MASS = {
    "D+": 3.3435837724e-27,
    "H+": 1.67262192595e-27,
    "He3+": 5.0082353373e-27,
    "He4+": 6.6464764e-27,
    "He2+": 6.6464764e-27,  # alpha particle
    "e-": 9.1093837139e-31,
}

# Species charge table [C]
SPECIES_CHARGE = {
    "D+": 1.602176634e-19,
    "H+": 1.602176634e-19,
    "He3+": 1.602176634e-19,
    "He4+": 2 * 1.602176634e-19,
    "He2+": 2 * 1.602176634e-19,
    "e-": -1.602176634e-19,
}


def _estimate_dt(config: SimConfig) -> float:
    """Estimate timestep from CFL condition.

    dt = dt_multiplier * min(dz, dr) / c, but for non-relativistic PIC
    we use the light speed CFL. In practice WarpX handles this internally,
    but we provide an estimate for the input file.
    """
    c = 299792458.0
    domain = config.nozzle.domain
    dz = (domain.z_max - domain.z_min) / config.nozzle.resolution.nz
    dr = domain.r_max / config.nozzle.resolution.nr
    return config.dt_multiplier * min(dz, dr) / c


def _config_hash(config: SimConfig) -> str:
    """SHA-256 hash of the configuration for reproducibility."""
    data = config.model_dump_json().encode()
    return hashlib.sha256(data).hexdigest()[:12]


def generate_warpx_input(config: SimConfig) -> str:
    """Generate a WarpX input script string from a SimConfig.

    Returns the input file content as a string. This can be written
    to disk and passed to WarpX via ``warpx.inputs``.
    """
    domain = config.nozzle.domain
    res = config.nozzle.resolution
    cfg_hash = _config_hash(config)
    has_electrons = "e-" in config.plasma.species

    # Random seed
    seed = config.random_seed
    if seed is None:
        seed = int(cfg_hash, 16) % (2**31)

    lines = [
        "# WarpX input file generated by MagNozzleX v0.1.0",
        f"# Config hash: {cfg_hash}",
        "#",
        "# Geometry: 2D RZ axisymmetric",
        f"# Nozzle type: {config.nozzle.type}",
        "",
        "################",
        "# GEOMETRY",
        "################",
        "geometry.dims = RZ",
        f"geometry.prob_lo = {domain.z_min} 0.0",
        f"geometry.prob_hi = {domain.z_max} {domain.r_max}",
        "",
        f"amr.n_cell = {res.nz} {res.nr}",
        "amr.max_level = 0",
        "",
        "################",
        "# BOUNDARY",
        "################",
        "boundary.field_lo = none pec",
        "boundary.field_hi = pml pml",
        "boundary.particle_lo = absorbing reflecting",
        "boundary.particle_hi = absorbing absorbing",
        "",
        "################",
        "# TIMESTEP",
        "################",
        f"max_step = {config.timesteps}",
        f"warpx.cfl = {config.dt_multiplier}",
        "",
        "################",
        "# PARTICLES",
        "################",
    ]

    species_names = []
    for sp in config.plasma.species:
        safe_name = sp.replace("+", "_plus").replace("-", "_minus")
        species_names.append(safe_name)

    lines.append(f"particles.species_names = {' '.join(species_names)}")
    lines.append("")

    eV_to_J = 1.602176634e-19

    for sp, safe_name in zip(config.plasma.species, species_names, strict=True):
        mass = SPECIES_MASS.get(sp)
        charge = SPECIES_CHARGE.get(sp)
        if mass is None or charge is None:
            lines.append(f"# WARNING: Unknown species {sp}, using placeholder values")
            mass = mass or 1.67262192595e-27
            charge = charge or 1.602176634e-19

        T_eV = config.plasma.T_e_eV if sp == "e-" else config.plasma.T_i_eV
        T_J = T_eV * eV_to_J
        v_th = math.sqrt(T_J / mass)

        lines.extend(
            [
                (
                    f"{safe_name}.species_type = proton"
                    if "+" in sp
                    else f"{safe_name}.species_type = electron"
                ),
                f"{safe_name}.mass = {mass:.10e}",
                f"{safe_name}.charge = {charge:.10e}",
                f"{safe_name}.injection_style = NUniformPerCell",
                f"{safe_name}.num_particles_per_cell = 64",
                f"{safe_name}.profile = constant",
                f"{safe_name}.density = {config.plasma.n0:.6e}",
                f"{safe_name}.momentum_distribution_type = gaussian",
                f"{safe_name}.uz_m = {config.plasma.v_injection_ms:.6e}",
                f"{safe_name}.ux_th = {v_th:.6e}",
                f"{safe_name}.uy_th = {v_th:.6e}",
                f"{safe_name}.uz_th = {v_th:.6e}",
                "",
            ]
        )

    # Mass ratio override
    if config.plasma.mass_ratio is not None and has_electrons:
        lines.append(f"# NOTE: Reduced mass ratio = {config.plasma.mass_ratio}")

    lines.extend(
        [
            "################",
            "# EXTERNAL B-FIELD",
            "################",
            "# Applied B-field is loaded from HDF5 file pre-computed by MagNozzleX",
            "# Use: warpx.read_fields_from_path = <bfield.h5>",
            "",
            "################",
            "# DIAGNOSTICS",
            "################",
            "diagnostics.diags_names = diag1",
            f"diag1.intervals = {config.diagnostics.field_dump_interval}",
            "diag1.diag_type = Full",
            "diag1.format = openpmd",
            "diag1.openpmd_backend = h5",
            "diag1.fields_to_plot = Br Bz Er Ez jr jz rho",
            "",
        ]
    )

    if config.diagnostics.mode == "analysis":
        lines.extend(
            [
                "diagnostics.diags_names = diag1 diag_particles",
                f"diag_particles.intervals = {config.diagnostics.particle_dump_interval}",
                "diag_particles.diag_type = Full",
                "diag_particles.format = openpmd",
                "diag_particles.openpmd_backend = h5",
                f"diag_particles.species = {' '.join(species_names)}",
                "",
            ]
        )

    lines.extend(
        [
            "################",
            "# REPRODUCIBILITY",
            "################",
            f"warpx.random_seed = {seed}",
            "warpx.verbose = 1",
        ]
    )

    return "\n".join(lines) + "\n"


def write_warpx_input(config: SimConfig, path: str | Path) -> Path:
    """Generate and write a WarpX input file.

    Returns the path to the written file.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = generate_warpx_input(config)
    path.write_text(content)
    return path
